### PR TITLE
Return data argument

### PR DESCRIPTION
**Pull request by baldrech**
Adding a `returnData` argument to all the plot's functions, allowing to return the data for the plot instead of the plot itself. This allows the plot's functions to fulfill a role of data processing function. The user can then plot the output in any way needed.

I am not sure how to run the tests though as the plot itself is not changing, just the function's output.  How should I do it?

### CODE REVIEW

**Comment by gustavdelius** [comment]
Hi Romain. Can you explain what you mean by "return the data for the plot" and give usage examples? The current plot functions also return the data for the plot, but in the form of a ggplot2 object. I am sure you mean to return the data in the form of a data frame. But then how does say `plotBiomass(params, returnData = TRUE)` differ from `melt(getBiomass(params))`? And could we modify the `getBiomass()` function instead of `plotBiomass()` to return the data in the desired form? That would seem to keep more to the current convention.

I believe this pull request has to do with the desire to be able to add more information to a plot after it has been created. Could the ggplot2 object returned by the plot functions be designed in such a way that the extra information can be added to it using the ggplot `+` syntax? Again, usage examples may help to understand this.

Regarding the testing: First you should describe in the roxygen comment of the function what the user can expect the function to return, then the tests should test that it really does so. So I guess in this case the documentation will say that the function when called with `returnData = TRUE` will return a data frame with such variable names and so many rows, and then the tests will test that the actual return value conforms to this. 

Here are some additional remarks:
1. The naming convention in mizer is that function names use camelCase but variable names do not. They should use underscores. So something like `return_data`.
2. Add usage example of the new feature in the examples section of the roxygen comment. Those too can be used as extra tests by asking R to run all examples with `devtools::run_examples(run_dontrun = TRUE)`.
3. As an extra check on your code, hit the "Check" button on the RStudio "Build" tab. That can flags up a variety of problems automatically.

**Comment by baldrech** [comment]
Hi Gustav,
Yes, I meant that the function returns the data in the form of a data frame ready to use by ggplot. The "plot" functions do not just melt the output of a "get" function and feed it to ggplot usually. If you look at `plotSpectra` for example there is a lot of data formatting before getting it ready for a ggplot. 

Since the formatting depends on arguments given to the "plot" function, I find it easier to use the "plot" function directly to return a data frame instead of a "get" function. Furthermore the "get" functions are used to run the model which require different formatted output, so I see more the "get" function outputting raw data that is then processed by other functions depending of what is needed and I do not want to edit it. I believe you implemented the `getBiomassFrame` for just this reason, a function using the `getBiomass` output and formatting it for a ggplot. The `returnData` argument is easier to implement than to write a new `getFrame` function for every "plot/get" function in my opinion.

It is true that we can add information to the ggplot2 object using `+` but if we overwrite some part of the plots we get warnings such as "x axis is already defined". Furthermore I am not sure how to delete unwanted information from the plot without using `ggplot_build`.

I hope this convince you of the utility of such an argument, in the meantime I will improve the pull request following your other comments.

**Comment by gustavdelius** [comment]
O.k., you have convinced me that the new argument is a good idea. I am looking forward to the updated code.

**Comment by gustavdelius** [comment]
This is no superseded by #191

**Pull request closed without merging**
