### PR TITLE
Adding starvation mortality

### PR DESCRIPTION
**Pull request by astaaudzi**
Here is my attempt to make a better pull request to add starvation mortality into mizer master. Unfortunately the code does not build because I don't know how to tell mizer that a new function getSMort() has been added. I used to modify namespace file manually, but that presumably is not the right way and does not work at the moment. We still need to add backwards compatibility  to ensure that results from earlier runs produce identical results. As far as I know starvation mortality has not been used in mizer for a few years now. So I am not sure whether starvation mortality should be optional, or how to enable it. Finally, at this stage starvation mortality is determined by one hardwired proportionality parameter. It is set to 0.1 and means that instantaneous mortality will be 1/year when energy deficit is equal to individual's weight. This assumption just follows Andersen's and Hartvig's earlier papers and original mizer vignette

### CODE REVIEW

**Comment by gustavdelius** [comment]
Thanks Asta. To export a function you add the @export tag to the roxygen documentation block for the function. You are right that the NAMESPACE file should not be edited by hand.

This is a continuation of #36. You usually don't need to create a new pull request after you modify the code of the original pull request. Once you push the modified code to the same branch from which the original pull request was created, that pull request will be automatically using your new code.

I believe the comments I made on #36 still apply to this.

**Comment by astaaudzi** [comment]
Thanks Gustav, I have now used correct @export option and the code runs. The original pull request has been created from a different branch that had many other modifications. This branch is now specifically made to add starvation mortality only. 
Some remaining issues that could or should be addressed: 
1) write tests to explore starvation mortality effects 
2) Move starvation mortality scaling parameter, which is currently hardwired into the code as 0.1, to species parameters 
3) Add plots or some output of starvation mortality for users to assess whether it ever applies 
4) Most importantly - decide how it could be incorporated into the main code ensuring replication of old results 

Regarding the comments in #36 - the current implementation of the code does not return negative growth. Once starvation mortality is calculated the negative growth is then turned to zero

**Comment by gustavdelius** [comment]
Thank you Asta. Regarding your point 4: by default the new parameter should be set so that there is no starvation mortality. Perhaps choose the parameter to be the strength of the starvation mortality, rather than its inverse, so that a value of 0 for the parameter means no starvation mortality.

**Comment by astaaudzi** [comment]
Hi Gustav. I think I will leave the point 4 up to the developers :) The current implementation just follows what mizer vingette used to say, and as far as remember @Kenhasteandersen assumed that starvation mortality was included anyway. The actual function to use and default conditions can be a matter for discussion.

**Pull request merged**
