### PR TITLE
Update documentation for r_pp

### PR DESCRIPTION
**Pull request by jaseeverett**
Have replaced "primary production" with "background resource spectrum" in the documentation

### CODE REVIEW

**Comment by gustavdelius** [comment]
Hi Jase. Thank you for this pull request. Give me an opportunity to discuss naming of things in mizer. Currently most of the documentation refers to the "plankton spectrum" rather than the "background resource spectrum". Do you have a view about this?

**Comment by jaseeverett** [comment]
No strong views. We generally call it "resource spectrum" but that is just what we learnt initially. Happy to change to "plankton spectrum"

**Comment by astaaudzi** [comment]
Good idea. Let's call it "background resource spectrum" everywhere

**Comment by maxlindmark** [comment]
How does the name "background resource spectrum" work in versions with a benthic spectrum?

**Comment by gustavdelius** [comment]
I propose that for now we stick with "plankton spectrum" and change to "resource spectra" once we have extended mizer to be able to handle multiple resource spectra, or once someone contributes a model where they have the need to use the plankton spectrum for something that is not plankton. When in the future we switch to "resource spectra", I don't think there is any need for the extra word "background", i.e., "background resource spectra" would not be any more informative than "resource spectra".

**Pull request merged**
